apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd-autopilot.argoproj-labs.io/default-dest-server: https://kubernetes.default.svc
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "-2"
  creationTimestamp: null
  name: boot
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: boot project
  destinations:
    - namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
status: {}

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: boot
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  creationTimestamp: null
spec:
  goTemplate: true
  generators:
    - git:
        files:
          - path: apps/*/boot.yaml
        repoURL: https://github.com/pchar/nxt-ops.git
        requeueAfterSeconds: 20
        revision: main
        template:
          metadata: {}
          spec:
            destination: {}
            project: ""
  syncPolicy: {}
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: '{{ default "0" .syncWave }}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io/foreground
      labels:
        app.kubernetes.io/managed-by: argocd-autopilot
        app.kubernetes.io/name: '{{ .appName }}'
      name: 'boot-{{ .userGivenName }}'
      namespace: argocd
    spec:
      project: boot
      destination:
        namespace: '{{ .destNamespace }}'
        server: '{{ .destServer }}'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - Validate=true
          - Wait=true
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          jsonPointers:
            - /status
    # <- IMPORTANT: templatePatch is a single string. Put your conditionals inside.
    templatePatch: |
      {{- if eq .type "helm" }}
      spec:
        sources:
          - repoURL: '{{ .helmChartURL }}'
            targetRevision: '{{ .helmChartVersion }}'
            chart: '{{ .helmChartName }}'
            helm:
              releaseName: '{{ .helmChartName }}'
              valueFiles:
                - $values/apps/{{ .helmChartName }}/values.yaml
          - repoURL: https://github.com/pchar/nxt-ops.git
            targetRevision: main
            ref: values
      {{- else if eq .type "dir" }}
      spec:
        source:
          repoURL: https://github.com/pchar/nxt-ops.git
          targetRevision: main
          path: 'apps/{{ .appName }}/templates/'
      {{- end }}
status: {}
