provider: webhook
interval: 60m
triggerLoopOnEvent: true
logLevel: debug
txtPrefix: "zzz-"
policy: upsert-only   # or "sync" for full sync (ie also deletions)
txtOwnerId: blah

extraArgs:
  webhook-provider-url: http://localhost:3333

sidecars:
  - name: he-webhook
    image: ghcr.io/waldner/external-dns-webhook-he:0.0.4   # or whatever
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 3333
        name: http
    livenessProbe:
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 10
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 10
      timeoutSeconds: 5
    env:
      - name: WEBHOOK_HE_LOG_LEVEL
        value: "info"
      - name: WEBHOOK_HE_USERNAME
        valueFrom:
          secretKeyRef:
            name: he-credentials
            key: username
      - name: WEBHOOK_HE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: he-credentials
            key: password
      - name: WEBHOOK_HE_DOMAIN_FILTER
        value: "nextmind.net"