persistence:
  # Used to store ACME data (acme.json) and anything else under /data
  enabled: true
  name: data
  # existingClaim: ""
  accessMode: ReadWriteOnce
  size: 128Mi
  # storageClass: ""
  # volumeName: ""
  path: /data
  annotations: {}
  # subPath: ""

# Certificates resolvers configuration (v33+)
certificatesResolvers:
  letsencrypt:
    acme:
      email: pch@nextmind.net
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web

service:
  spec:
    externalTrafficPolicy: Local
