apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: boot-test
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: https://github.com/pchar/nxt-ops.git
      revision: main
      requeueAfterSeconds: 20
      files:
        - path: apps/*/boot-dir.yaml

  # ✅ Progressive syncs use RollingSync + rollingSync
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: env
              operator: In
              values: ["dev"]
          maxUpdate: 1
        # add more steps as needed
        # - matchExpressions:
        #     - key: env
        #       operator: In
        #       values: ["qa"]
        #   maxUpdate: 100%
        # - matchExpressions:
        #     - key: env
        #       operator: In
        #       values: ["prod"]
        #   maxUpdate: 10%

  template:
    metadata:
      name: boot-{{ .userGivenName }}
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: '{{ default "0" .syncWave }}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io/foreground
      labels:
        app.kubernetes.io/managed-by: argocd-autopilot
        app.kubernetes.io/name: '{{ .appName }}'
        # ✅ This label is what your matchExpressions select on
        env: '{{ default "dev" .env }}'
    spec:
      project: boot
      destination:
        name: in-cluster
        namespace: '{{ .destNamespace }}'
      source:
        repoURL: https://github.com/pchar/nxt-ops.git
        targetRevision: main
        path: apps/{{ .appName }}/templates/
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - Validate=true
          - Wait=true
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          jsonPointers: ["/status"]
