apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
  labels:
    app.kubernetes.io/managed-by: argocd-autopilot
    app.kubernetes.io/name: metallb-pools
    envLabel: dev
  name: boot-metallb-pools
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: metallb
  project: default
  source:
    path: apps/metallb-pools/templates/
    repoURL: https://github.com/pchar/nxt-ops.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
