apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd-autopilot.argoproj-labs.io/default-dest-server: {{ .destinationServer }}
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "-2"
  creationTimestamp: null
  name: {{ .project }}
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: {{ .project }} project
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
status: {}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .project }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  goTemplate: true
  generators:
    - git:
        files:
          - path: values/*/{{ .project }}.yaml
        repoURL: https://github.com/pchar/nxt-ops.git
        requeueAfterSeconds: 20
        revision: main
        template:
          metadata: {}
          spec:
            destination: {}
            project: ""
  syncPolicy: {}
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: '{{ default "0" .syncWave }}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io/foreground
      labels:
        app.kubernetes.io/managed-by: argocd-autopilot
        app.kubernetes.io/name: '{{ .appName }}'
      name: '{{ .project }}-{{ .userGivenName }}'
      namespace: argocd
    spec:
      project: {{ .project }}
      destination:
        name: {{ .destinationCluster }}
        namespace: '{{ .destNamespace }}'
      sources:
        - repoURL: '{{ .helmChartURL }}'
          targetRevision: '{{ .helmChartVersion }}'
          chart: '{{ .helmChartName }}'
          helm:
            releaseName: '{{ .helmChartName }}'
            valueFiles:
              - $values/apps/{{ .helmChartName }}/{{ .project }}.yaml
        - repoURL: https://github.com/pchar/nxt-ops.git
          targetRevision: main
          ref: values
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - Validate=true
          - Wait=true
      ignoreDifferences:
        - group: argoproj.io
          jsonPointers:
            - /status
          kind: Application
status: {}